

spring:
  cloud:
    gateway:
      routes:
      - id: microservicios-usuarios
        uri: lb://microservicios-usuarios
        predicates:
        - Path=/api/alumnos/**
        filters:
        - StripPrefix=2