

spring:
  cloud:
    gateway:
      routes:
      - id: microservicios-usuarios
        uri: lb://microservicios-usuarios
        predicates:
        - Path=/api/alumnos/**
        filters:
        - StripPrefix=2
      - id: microservicios-cursos
        uri: lb://microservicios-cursos
        predicates:
        - Path=/api/cursos/**
        filters:
        - StripPrefix=2
      - id: microservicio-examenes
        uri: lb://microservicio-examenes
        predicates:
        - Path=/api/examenes/**
        filters:
        - StripPrefix=2
